### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by blancnacarat** [zachwinter/kaleidosync#1]
Recurring error : 

text "Syncing..." appears, then after 2s the text vanish, the artwork of the playing song is not displayed and the animation stays frozen. After refreshing the page the problem is usually solved but it tends to happen a lot.

console log

"jQuery.Deferred exception: e.metadata is undefined a@moz-extension://a7a897c3-c193-994e-88c0-9dc1116fcae4/h1-main.js:1:144384
[153]/h/<@moz-extension://a7a897c3-c193-994e-88c0-9dc1116fcae4/h1-main.js:1:142139
l@moz-extension://a7a897c3-c193-994e-88c0-9dc1116fcae4/h1-vendor.js:48:25138
Deferred/then/i/</c<@moz-extension://a7a897c3-c193-994e-88c0-9dc1116fcae4/h1-vendor.js:48:25454
 undefined"

-- EDIT : screenshot

![screen shot 2018-09-24 at 09 53 13](https://user-images.githubusercontent.com/41341942/45934291-b4661000-bfdf-11e8-80c7-48bf04b21a51.png)

**Comment by zachwinter** [comment]
Strange... jQuery isn't part of this project at all. Could you provide me with any more info?

Thanks for taking the time to create an issue!

**Comment by blancnacarat** [comment]
Little update:
You're right, I think the jQuery error isn't relevant indeed and might be linked to Firefox, when switching browsers it doesn't persist.
However the syncing error is for real, but a more appropriate issue would be

 console log :

XML Parsing Error: not well-formed
Location: https://api.spotify.com/v1/audio-analysis/4YA0OHXqNGyNCTD4Mybpvq
Line Number 1, Column 1:

from link :


{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}

![screen shot 2018-09-24 at 09 48 28](https://user-images.githubusercontent.com/41341942/45934248-0f4b3780-bfdf-11e8-9f17-cbcfea336b1a.png)
![screen shot 2018-09-24 at 09 48 42](https://user-images.githubusercontent.com/41341942/45934249-0f4b3780-bfdf-11e8-80ec-e1fad56f31d8.png)

Paul

**Comment by zachwinter** [comment]
This is fixed in production. 👍
