### ISSUE TITLE
Redirecting to "http://localhost:8080/undefined/login?auth_id=undefined"

### ISSUE THREAD

**Issue by russellkim98** [zachwinter/kaleidosync#13]
Steps to reproduce the issue:
1) Clone repo
2) Create '.env' while replacing client_id and redirect_uri
3) Run 'npm i'
4) Run 'npm run serve'
5) localhost page is blank except for "Illegal_redirect_uri"
6) go to login.js and manually change the client id and redirect uri
7) Login page shows up, then "Session expired, logging back in", then the page "http://localhost:8080/undefined/login?auth_id=undefined", which is blank. 

Any help?

**Comment by zachwinter** [comment]
Can you show me what you have in your .env file?

**Comment by zachwinter** [comment]
Closing this for now – if you need help feel free to reach out to me on Telegram (@yozic).
