### ISSUE TITLE
Failing to get the audio analysis for a track breaks Spotify integration

### ISSUE THREAD

**Issue by theminecoder** [zachwinter/kaleidosync#14]
If the app cant get a valid audio analysis from Spotify (504 error/network error) it throws an unhandled premise rejection which then causes the app to stop working. It no longer refreshes the player stats from Spotify nor reattempts to get the audio analysis.

This is fixed by refreshing but can become a nuisance if trying to use it on a projector/tv in an hands off environment.

**Comment by zachwinter** [comment]
Thanks for filing the bug! I imagine this is a rare one.

Just pushed a change that catches that error and returns another call to `this.ping()`; if that call fails, the browser will refresh.
