### ISSUE TITLE
Integrate lyrics

### ISSUE THREAD

**Issue by mrtysn** [zachwinter/kaleidosync#15]
It would be great to have synced lyrics with these visuals like the old Winamp + Minilyrics days. Throwing out the idea here and I'm willing to work on it if you have some pointers to start with.

**Comment by machmar** [comment]
yeah!

**Comment by zachwinter** [comment]
Do you know of any free APIs that could drive this?

**Comment by GeorgiaPeanuts** [comment]
Hopefully when Spotify expands their new lyrics feature (which uses musixmatch API) to more markets including the US, they'll add a way to access it on their API

**Comment by zachwinter** [comment]
> Hopefully when Spotify expands their new lyrics feature (which uses musixmatch API) to more markets including the US, they'll add a way to access it on their API

That'd be awesome!
