### ISSUE TITLE
[Suggestion] Pull Colors from Album Artwork

### ISSUE THREAD

**Issue by SterlingButters** [zachwinter/kaleidosync#2]
Thought this would be a cool feature

**Comment by mauriciabad** [comment]
It is, but then the color will be changed, so it doesn't matter.

**Comment by zachwinter** [comment]
I've played this idea using various color libraries; the end result is never quite as nice as one would hope unless the artwork is primarily only a few colors. I'll play with it some more when I get the time – gonna close this for now though.

Thanks for the feedback!

**Comment by DanSolo81** [comment]
What about different color palettes based on different themes?  Like you could have natural, muted colors, vibrant neon colors, a standard rainbow, pastels, etc.  For example, natural and muted colors when playing country or classic rock.  Or standard rainbow for more poppy music.  Bright and vibrant neons when playing EDM or Retro/Synth/Dreamwave type music.  Essentially colors to compliment types of music and thus complimenting the setting or mood the listener is going for.
