### ISSUE TITLE
Hide the mouse

### ISSUE THREAD

**Issue by mauriciabad** [zachwinter/kaleidosync#3]
Hide the mouse when isn't moving, so it doesn't disturb.

**Comment by zachwinter** [comment]
Don't know why I haven't done this already! Thank you – will push a fix for this soon.

**Comment by DanSolo81** [comment]
Hey guys, I made another suggestion that could work with this suggestion.  When the mouse or trackpad is disturbed and the cursor appears on screen, so would the band and song name of the song currently playing.  After 5-10 seconds the cursor and track information disappear.

**Comment by zachwinter** [comment]
I've built a new UI that adds this feature. It's still not ready for me to redirect the existing Heroku app (there are a couple outstanding bugs), but you can check it out here:

https://www.kaleidosync.com

Feedback is highly appreciated. <3
