### ISSUE TITLE
Unusable CPU utilization

### ISSUE THREAD

**Issue by bedazzler** [zachwinter/kaleidosync#36]
I love the idea of app but this latest version causes my system to lag like no other. As soon as I open a visualization my CPU utilization hits 90% making this app unusable for me.

Here is a screenshot of my system running Spotify and Chrome:
![image](https://user-images.githubusercontent.com/22353639/105934278-bd7aa800-6004-11eb-8039-8876684dc56e.png)

And another of my system running Spotify and Chrome but with Kaleidosync running:
![image](https://user-images.githubusercontent.com/22353639/105934460-1a765e00-6005-11eb-822e-1262126d20cd.png)

The utilization dips immediately if I navigate to a different tab without Kaleidosync running or if I close it.

**Comment by bedazzler** [comment]
Just as an update - my work 2019 macbook pro handles this app perfectly so it might be a chip architecture thing.

**Comment by zachwinter** [comment]
Strange – it looks like you're not getting any sort of hardware acceleration (1% NVIDIA GPU utilization) on the Windows machine. Do you maybe accidentally have hardware acceleration disabled in Chrome?
