### ISSUE TITLE
[Suggestion] Full Screen Mode

### ISSUE THREAD

**Issue by DanSolo81** [zachwinter/kaleidosync#4]
When in browser and you enter full screen mode, the browser toolbar and open tabs are still visible.  Is it possible to add an Expand button < > or [  ] to enter a full screen mode that will take up the entire screen with the visualizer?

**Comment by TheLawsOfChaos** [comment]
So I mean, F11 (shortcut to put most, if not all browsers into full screen mode) for me hides the toolbar and any open tabs. What browser do you see this not work in?

**Comment by zachwinter** [comment]
I've built a new UI that adds this feature. It's still not ready for me to redirect the existing Heroku app (there are a couple outstanding bugs), but you can check it out here:

https://www.kaleidosync.com

Feedback is highly appreciated. <3
