### ISSUE TITLE
Kaleidosync doesn't show up in Spotify "Connect to device" section

### ISSUE THREAD

**Issue by 0xnsepp** [zachwinter/kaleidosync#43]
I cannot get Kaleidosync to show up in the "Connect to Device" section. 

I tried to use Kaleidosync on multiple Browsers (Firefox, Edge, Brave), all of them do not work :(
If i start the Spotify Webplayer on those Browsers, they immediately show up on the "Connect to device" section. I tried to "see" the Kaleidosync "Device" in the Desktop App (non-Windows Store Version), iOS App and on the Web Player. 

Any Ideas? :'D

**Comment by dolphinchenle** [comment]
i'm having this issue as well.

**Comment by idkgamedev** [comment]
Same. I tried refreshing, using the desktop version, Nothing.

**Comment by zachwinter** [comment]
Fixed, y'all!
