### ISSUE TITLE
Disabling "auto-hide toolbar" doesn't seem to do anything

### ISSUE THREAD

**Issue by iameli** [zachwinter/kaleidosync#45]
I'd like the currently-playing song to stay on the screen, and that is kinda implied by disabling the "auto-hide toolbar" option? But it still goes away.

**Comment by The-RIPster** [comment]
Same here. Tried everything. I'm using Mac OS 10.15.7 and it behaves the same on my two browsers Safari and Chrome. Any tricks to get it working besides installing some kind of "auto mouse move" software?
