### ISSUE TITLE
Kaleidosync not working for me, I tried to sign in, it got signed in but it wasn't detected on Spotify on the devices section. Please help

### ISSUE THREAD

**Issue by kanaguyashwanth** [zachwinter/kaleidosync#47]

**Comment by PwccaCode** [comment]
having the same issue.

**Comment by Batshua** [comment]
It only sort of works for me on Mac OS X 10.15.7 (Catalina). It doesn’t work in Chrome, Firefox, and Opera. It sorta-works in Safari. The browsers and app can’t find it as an output but it logs in and pulls the songs. It won’t go full screen, though.

**Comment by Xardous** [comment]
Same issue here.

**Comment by Ihernandezpi** [comment]
Same issue

**Comment by firepro20** [comment]
In which browser does it work exactly?

**Comment by DevAmiyo** [comment]
same issue.. spotify isn't detecting.. I tried running spotify both on web and the app

**Comment by firepro20** [comment]
I ended up using VSxu on Steam

**Comment by zachwinter** [comment]
It's working now, y'all!

**Comment by firepro20** [comment]
I'll give it a try, thanks!

**Comment by firepro20** [comment]
Yep definitely working, amazing 💯
