### ISSUE TITLE
[Suggestion] Track Info

### ISSUE THREAD

**Issue by DanSolo81** [zachwinter/kaleidosync#5]
An additional suggestion, piggybacking off of the mouse request, when moving the cursor over the visualizer is it possible to display the song and band name of the track currently playing?  It could then go away after 5 seconds of the mouse/trackpad not being disturbed.

**Comment by zachwinter** [comment]
I've built a new UI that adds this feature. It's still not ready for me to redirect the existing Heroku app (there are a couple outstanding bugs), but you can check it out here:

https://www.kaleidosync.com

Feedback is highly appreciated. <3
