### ISSUE TITLE
Feature Request: Lyrics overlay

### ISSUE THREAD

**Issue by bedazzler** [zachwinter/kaleidosync#52]
It would be awesome to have the lyrics pulled in from Genius when fullscreen through Kaleidosync to karaoke.

**Comment by Hardik-hi** [comment]
I think this can help in this. https://developer.musixmatch.com/documentation @zachwinter can I take up on this feature?

**Comment by zachwinter** [comment]
@Hardik-hi thank you for opening this!

Short answer: yes, absolutely! Long answer: shoot me an email? contact@zachwinter.com

This repo isn't even up to date. I really need to fix that.
