### ISSUE TITLE
How do run it on my website!

### ISSUE THREAD

**Issue by acujl** [zachwinter/kaleidosync#6]
Heya! I want to run it on my website! IT's hosted with apache. 

Tried to move (to my hosting) and oppening it up on web browser but can't get it working :( How did you managed to get it up and running?

**Comment by TheLawsOfChaos** [comment]
Did you follow the 'run locally' instructions?

**Comment by acujl** [comment]
Yup.. Couldn't get it running

**Comment by zachwinter** [comment]
Do you still need help with this? Feel free to message me on Telegram (@yozic).
