### ISSUE TITLE
Against Spotify's ToS?

### ISSUE THREAD

**Issue by Cobertos** [zachwinter/kaleidosync#72]
Seems like syncing anything to visuals is against Spotify's ToS?

Section III, bullet 6: https://developer.spotify.com/policy/#iii-some-prohibited-applications

Cool site though!

**Comment by zachwinter** [comment]
Good eye! I think I've gotten a pass, though – I've done a couple gigs where Spotify was involved. It's hard to imagine they didn't see the project.
