### ISSUE TITLE
Enhancement: Pallet Choices

### ISSUE THREAD

**Issue by TheLawsOfChaos** [zachwinter/kaleidosync#8]
I know you're auto-magically pulling the data via NEST's already doing the math, and I see where you are declaring the colorSchemes, but maybe allow for dynamic user input to pick a scheme (or picker of schemes). For example, I'm hooking this up to a Philips Hue Sync app and showing lights, so the darker more vibrant (i.e. less white) is better for what I want. Would be a cool feature.

Makes me almost want to run this myself to edit the schemes ;)

**Comment by zachwinter** [comment]
I did a UI overhaul recently (see https://www.kaleidosync.com, still in "beta") that had a theme creator, but I decided to omit it for UX reasons. I might re-add it in the future. I also played with some libraries that created color schemes by sampling the album artwork, but the end result was pretty shitty. 

The Hue lights are super fun, aren't they? I recently integrated with them as well; would love to hear what you've thrown together. Are you using the Lights API or the Entertainment API?

**Comment by TheLawsOfChaos** [comment]
I totally get that, album art isn't always the best choice on color pallet choice. And I can see keeping the UX of the whole thing very clean by having the limited options.

And yeah, it was great honestly. When I have folks come over for a party/drinks etc, I put the living room TV on this, and play spotify, with my hue lights syncing to the screen. Really creates nice ambiance. So really appreciate all that you do.

**Comment by zachwinter** [comment]
It can work pretty well for the "Apple-esque" blurred background look – but their engineers do an infinitely better job isolating small color highlights that would otherwise be blurred by interpolation or what have you. Maybe JS just isn't fast enough to do it properly? Not sure. 

It's my pleasure, seriously. I had no idea so many people would appreciate this project.
